In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

## EDA

In [2]:
df = pd.read_csv('breastCancer_data.csv')
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [3]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

Check for dupliacted data

In [5]:
df.duplicated().sum()

np.int64(0)

Check for null data

In [6]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

Drop columns

In [7]:
df.drop(columns={'id', 'Unnamed: 32'}, inplace=True)

In [8]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [9]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [10]:
df['diagnosis'] = df['diagnosis'].map({'M':1, 'B':0})

Splitting data into Training, Validation and Test set

In [11]:
train_val_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
train_df, val_df = train_test_split(train_val_df, test_size=0.25, random_state=42)

In [13]:
target_col = 'diagnosis'
input_cols = list(train_df.columns)[1:]

In [14]:
train_inputs = train_df[input_cols].copy()
train_target = train_df[target_col].copy()

val_inputs = val_df[input_cols].copy()
val_target = val_df[target_col].copy()

test_inputs = test_df[input_cols].copy()
test_target = test_df[target_col].copy()

In [15]:
print(train_df.shape[0], val_df.shape[0], test_df.shape[0])

341 114 114


## Logistic Regression

In [39]:
LR_model = LogisticRegression(solver='liblinear')

LR_model.fit(train_inputs, train_target)

LogisticRegression(solver='liblinear')

In [40]:
LR_model.coef_

array([[-2.16929863e+00, -1.03504866e-01,  1.69351027e-01,
         4.09287387e-04,  1.26894024e-01,  4.17556762e-01,
         6.57815966e-01,  3.19770512e-01,  1.87089880e-01,
         2.83143845e-02,  1.98838209e-02, -1.43346174e+00,
         2.24578170e-01,  6.55814763e-02,  1.53238358e-02,
         2.51795817e-02,  7.41126763e-02,  3.60638982e-02,
         4.08751140e-02, -1.59882317e-03, -1.23695953e+00,
         3.83174455e-01,  1.67228939e-02,  2.81166365e-02,
         2.40073061e-01,  1.25834071e+00,  1.67423240e+00,
         5.79028850e-01,  6.93278695e-01,  1.24763696e-01]])

In [41]:
LR_model.intercept_

array([-0.41420592])

Accuracy

In [42]:
print(f'Training Accuracy: {LR_model.score(train_inputs, train_target)}')

Training Accuracy: 0.9589442815249267


In [43]:
print(f'Validation Accuracy: {LR_model.score(val_inputs, val_target)}')

Validation Accuracy: 0.9649122807017544


Confusion Matrix

In [44]:
pd.DataFrame(confusion_matrix(train_target, LR_model.predict(train_inputs)))

0    1
0  211    5
1    9  116

In [45]:
pd.DataFrame(confusion_matrix(val_target, LR_model.predict(val_inputs)))

0   1
0  68   2
1   2  42

Create a dataframe to compare Actual and Predicted output of the Training dataset

In [46]:
LR_df = train_df.copy()

LR_df['Predicted'] = LR_model.predict(train_inputs)

In [47]:
print('Logistic Regression Prediction')
LR_df[['diagnosis', 'Predicted']]

Logistic Regression Prediction


diagnosis  Predicted
217          0          0
283          1          1
0            1          1
504          0          0
251          0          0
..         ...        ...
57           1          1
492          1          1
418          0          0
385          1          0
325          0          0

[341 rows x 2 columns]

## Decision Tree

In [48]:
DecisionTree_model = DecisionTreeClassifier(random_state=42)

DecisionTree_model.fit(train_inputs, train_target)

DecisionTreeClassifier(random_state=42)

Feature Importances

In [60]:
feature_importances_df = pd.DataFrame({
    'Feature': train_inputs.columns,
    'Importance': DecisionTree_model.feature_importances_
}).sort_values(by='Importance', ascending=False)


In [61]:
feature_importances_df

Feature  Importance
27     concave points_worst    0.709053
23               area_worst    0.146160
21            texture_worst    0.043336
9    fractal_dimension_mean    0.028944
13                  area_se    0.024260
0               radius_mean    0.023852
26          concavity_worst    0.012508
11               texture_se    0.011887
3                 area_mean    0.000000
6            concavity_mean    0.000000
5          compactness_mean    0.000000
4           smoothness_mean    0.000000
2            perimeter_mean    0.000000
1              texture_mean    0.000000
12             perimeter_se    0.000000
10                radius_se    0.000000
7       concave points_mean    0.000000
8             symmetry_mean    0.000000
17        concave points_se    0.000000
14            smoothness_se    0.000000
16             concavity_se    0.000000
15           compactness_se    0.000000
20             radius_worst    0.000000
19     fractal_dimension_se    0.000000
18              symmetry_se    0.000000
22          perimeter_worst    0.000000
25        compactness_worst    0.000000
24         smoothness_worst    0.000000
28           symmetry_worst    0.000000
29  fractal_dimension_worst    0.000000

Accuracy

In [62]:
DecisionTree_model.score(train_inputs, train_target)

1.0

In [63]:
DecisionTree_model.score(val_inputs, val_target)

0.9298245614035088

Confusion matrix

In [64]:
confusion_matrix(train_target, DecisionTree_model.predict(train_inputs))

array([[216,   0],
       [  0, 125]])

In [65]:
confusion_matrix(val_target, DecisionTree_model.predict(val_inputs))

array([[64,  6],
       [ 2, 42]])

In [67]:
DecisionTree_model.tree_.max_depth

6

Hyperparameters Tuning

Function to find the best max_depth

In [77]:
def max_depth_error(md):
    model = DecisionTreeClassifier(max_depth=md, random_state=42)
    model.fit(train_inputs, train_target)
    train_acc = model.score(train_inputs, train_target)
    val_acc = model.score(val_inputs, val_target)
    return {'Max Depth': md, 'Training Accuracy': train_acc, 'Validation Accuracy': val_acc}

In [78]:
accuracy_df = pd.DataFrame([max_depth_error(md) for md in range(1, 7)])

In [79]:
accuracy_df.sort_values('Validation Accuracy', ascending=False)

Max Depth  Training Accuracy  Validation Accuracy
3          4           0.985337             0.929825
2          3           0.979472             0.929825
4          5           0.994135             0.929825
5          6           1.000000             0.929825
1          2           0.967742             0.921053
0          1           0.923754             0.912281

In [80]:
DecisionTree_model = DecisionTreeClassifier(random_state=42, max_depth=4)

DecisionTree_model.fit(train_inputs, train_target)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [81]:
DecisionTree_model.score(train_inputs, train_target)

0.9853372434017595

In [82]:
DecisionTree_model.score(val_inputs, val_target)

0.9298245614035088

## Random Forest

In [83]:
RF_model = RandomForestClassifier(random_state=42)

RF_model.fit(train_inputs, train_target)

RandomForestClassifier(random_state=42)

Feature's Importances

In [85]:
feature_importances_df2 = pd.DataFrame(
    {'Features': train_inputs.columns,
     'Importances':RF_model.feature_importances_}
    ).sort_values('Importances', ascending=False)

In [86]:
feature_importances_df2

Features  Importances
27     concave points_worst     0.171832
23               area_worst     0.143535
7       concave points_mean     0.098463
6            concavity_mean     0.079760
3                 area_mean     0.062985
20             radius_worst     0.061149
22          perimeter_worst     0.055284
2            perimeter_mean     0.049387
26          concavity_worst     0.045170
0               radius_mean     0.039311
21            texture_worst     0.029879
13                  area_se     0.019882
25        compactness_worst     0.019707
1              texture_mean     0.014232
5          compactness_mean     0.014102
10                radius_se     0.013356
28           symmetry_worst     0.011767
24         smoothness_worst     0.011550
29  fractal_dimension_worst     0.008384
14            smoothness_se     0.006102
12             perimeter_se     0.005928
16             concavity_se     0.005526
17        concave points_se     0.005167
9    fractal_dimension_mean     0.005027
19     fractal_dimension_se     0.004420
11               texture_se     0.004351
4           smoothness_mean     0.004288
15           compactness_se     0.003490
18              symmetry_se     0.003365
8             symmetry_mean     0.002599

Accuracy

In [87]:
RF_model.score(train_inputs, train_target)

1.0

In [88]:
RF_model.score(val_inputs, val_target)

0.956140350877193

Confusion Matrix

In [89]:
confusion_matrix(train_target, RF_model.predict(train_inputs))

array([[216,   0],
       [  0, 125]])

In [90]:
confusion_matrix(val_target, RF_model.predict(val_inputs))

array([[67,  3],
       [ 2, 42]])

Hyperparameters Tuning

In [136]:
RF_model = RandomForestClassifier(n_jobs=-1, random_state=42, n_estimators=10, max_depth=4, class_weight='balanced')

RF_model.fit(train_inputs, train_target)

RandomForestClassifier(class_weight='balanced', max_depth=4, n_estimators=10,
                       n_jobs=-1, random_state=42)

In [137]:
RF_model.score(train_inputs, train_target)

0.9912023460410557

In [138]:
RF_model.score(val_inputs, val_target)

0.9649122807017544

## Comparing Models

In [143]:
train_accuracy = [LR_model.score(train_inputs, train_target), DecisionTree_model.score(train_inputs, train_target), RF_model.score(train_inputs, train_target)]
val_accuracy = [LR_model.score(val_inputs, val_target), DecisionTree_model.score(val_inputs, val_target), RF_model.score(val_inputs, val_target)]

model_accuracy_df = pd.DataFrame({
    'Model': ['LogisticRegression', 'DecisionTree', 'RandomForest'],
    'Train_Accuracy': train_accuracy,
    'Val_Accuracy': val_accuracy
    })

In [144]:
model_accuracy_df

Model  Train_Accuracy  Val_Accuracy
0  LogisticRegression        0.958944      0.964912
1        DecisionTree        0.985337      0.929825
2        RandomForest        0.991202      0.964912